"use client";

import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { Navbar } from "@/components/Navbar";
import { HeroText } from "@/components/HeroText";
import { useAuth } from "@/context/auth";
import { Zap, Flame, Target, GitCommit, Briefcase, Sparkles } from "lucide-react";

const GITHUB_LOGIN_URL = `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/api/auth/github/login`;

const FEATURES = [
  {
    icon: Zap,
    title: "Earn XP",
    desc: "Every commit and LeetCode solve rewards real XP. Streak multipliers push it higher.",
    color: "#f59e0b",
  },
  {
    icon: Flame,
    title: "Build Streaks",
    desc: "Code every day. Your GitHub and LeetCode streaks are tracked independently.",
    color: "#f97316",
  },
  {
    icon: Target,
    title: "Daily Quests",
    desc: "Push a commit. Solve a problem. Daily goals auto-complete when you ship.",
    color: "#22c55e",
  },
  {
    icon: GitCommit,
    title: "GitHub Activity",
    desc: "Commits, pushes, and repo events pulled live via webhook — nothing to do manually.",
    color: "#6366f1",
  },
  {
    icon: Briefcase,
    title: "Job Tracker",
    desc: "Kanban board for your job search. Move cards from Applied to Offer.",
    color: "#ec4899",
  },
  {
    icon: Sparkles,
    title: "AI Digest",
    desc: "Weekly summary of your progress, wins, and gaps — generated by Claude.",
    color: "#8b5cf6",
  },
];

const STEPS = [
  { n: "1", title: "Connect GitHub", desc: "One OAuth click. We pull your activity automatically." },
  { n: "2", title: "Code every day", desc: "Commits, LeetCode solves, and goals all earn XP." },
  { n: "3", title: "Level up", desc: "Watch your level rise. Hit streaks. Clear the board." },
];

export default function Home() {
  const { isAuthenticated } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (isAuthenticated) router.replace("/dashboard");
  }, [isAuthenticated, router]);

  return (
    <div className="flex min-h-screen flex-col bg-base-100">
      <Navbar />

      <main className="flex flex-1 flex-col items-center text-center px-4 pt-32 pb-24 gap-20">

        {/* Hero */}
        <div className="flex flex-col items-center gap-5">
          <HeroText />
          <p className="max-w-md text-xl font-bold text-base-content/50">
            Your developer command center. XP, streaks, goals, and a job board — all in one place.
          </p>
          <a
            href={GITHUB_LOGIN_URL}
            className="btn btn-lg gap-3 font-black text-white border-none mt-2"
            style={{
              backgroundColor: "var(--game-accent)",
              boxShadow: "0 6px 0 color-mix(in srgb, var(--game-accent) 50%, #000)",
            }}
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
            </svg>
            Get started with GitHub
          </a>
        </div>

        {/* Features */}
        <section id="features" className="w-full max-w-3xl flex flex-col gap-6">
          <h2 className="text-2xl font-black text-base-content">Everything in one place</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map(({ icon: Icon, title, desc, color }) => (
              <div
                key={title}
                className="rounded-2xl bg-base-100 border-2 border-base-300 p-5 flex flex-col items-start gap-3 text-left"
                style={{ boxShadow: "0 4px 0 rgba(0,0,0,0.08)" }}
              >
                <div
                  className="rounded-xl p-2.5"
                  style={{ backgroundColor: `${color}18` }}
                >
                  <Icon size={20} style={{ color }} />
                </div>
                <div className="flex flex-col gap-1">
                  <p className="font-black text-base text-base-content">{title}</p>
                  <p className="text-sm font-semibold text-base-content/50 leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* How it works */}
        <section id="about" className="w-full max-w-3xl flex flex-col gap-6">
          <h2 className="text-2xl font-black text-base-content">How it works</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {STEPS.map(({ n, title, desc }) => (
              <div
                key={n}
                className="rounded-2xl bg-base-100 border-2 border-base-300 p-5 flex flex-col gap-3"
                style={{ boxShadow: "0 4px 0 rgba(0,0,0,0.08)" }}
              >
                <span
                  className="font-mono text-3xl font-black"
                  style={{ color: "var(--game-accent)" }}
                >
                  {n}
                </span>
                <div className="flex flex-col gap-1">
                  <p className="font-black text-base text-base-content">{title}</p>
                  <p className="text-sm font-semibold text-base-content/50">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

      </main>
    </div>
  );
}
