"""initial schema

Revision ID: 70dcf821201e
Revises:
Create Date: 2026-08-19 23:58:01.785008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dcf821201e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leetcode_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leetcode_problems_leetcode_id'), 'leetcode_problems', ['leetcode_id'], unique=True)
    op.create_index(op.f('ix_leetcode_problems_slug'), 'leetcode_problems', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.String(length=64), nullable=False),
    sa.Column('github_login', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('leetcode_username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('github_access_token', sa.String(length=512), nullable=True),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('pending_level_up', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('current', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('goal_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=256), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('leetcode_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['leetcode_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_review_user_problem')
    )
    op.create_index(op.f('ix_leetcode_reviews_next_review_at'), 'leetcode_reviews', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_leetcode_reviews_problem_id'), 'leetcode_reviews', ['problem_id'], unique=False)
    op.create_index(op.f('ix_leetcode_reviews_user_id'), 'leetcode_reviews', ['user_id'], unique=False)
    op.create_table('leetcode_solves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('time_complexity', sa.String(length=64), nullable=True),
    sa.Column('space_complexity', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['leetcode_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leetcode_solves_problem_id'), 'leetcode_solves', ['problem_id'], unique=False)
    op.create_index(op.f('ix_leetcode_solves_user_id'), 'leetcode_solves', ['user_id'], unique=False)
    op.create_table('leetcode_todo_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_todolist_user_name')
    )
    op.create_index(op.f('ix_leetcode_todo_lists_user_id'), 'leetcode_todo_lists', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('longest', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('notified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('leetcode_todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['leetcode_todo_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['leetcode_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'problem_id', name='uq_todo_user_problem')
    )
    op.create_index(op.f('ix_leetcode_todos_list_id'), 'leetcode_todos', ['list_id'], unique=False)
    op.create_index(op.f('ix_leetcode_todos_problem_id'), 'leetcode_todos', ['problem_id'], unique=False)
    op.create_index(op.f('ix_leetcode_todos_user_id'), 'leetcode_todos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leetcode_todos_user_id'), table_name='leetcode_todos')
    op.drop_index(op.f('ix_leetcode_todos_problem_id'), table_name='leetcode_todos')
    op.drop_index(op.f('ix_leetcode_todos_list_id'), table_name='leetcode_todos')
    op.drop_table('leetcode_todos')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_leetcode_todo_lists_user_id'), table_name='leetcode_todo_lists')
    op.drop_table('leetcode_todo_lists')
    op.drop_index(op.f('ix_leetcode_solves_user_id'), table_name='leetcode_solves')
    op.drop_index(op.f('ix_leetcode_solves_problem_id'), table_name='leetcode_solves')
    op.drop_table('leetcode_solves')
    op.drop_index(op.f('ix_leetcode_reviews_user_id'), table_name='leetcode_reviews')
    op.drop_index(op.f('ix_leetcode_reviews_problem_id'), table_name='leetcode_reviews')
    op.drop_index(op.f('ix_leetcode_reviews_next_review_at'), table_name='leetcode_reviews')
    op.drop_table('leetcode_reviews')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_leetcode_problems_slug'), table_name='leetcode_problems')
    op.drop_index(op.f('ix_leetcode_problems_leetcode_id'), table_name='leetcode_problems')
    op.drop_table('leetcode_problems')
    # ### end Alembic commands ###
